CREATE TABLE `crypt400` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `IP` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `crypt400` (`IP`) VALUES ('DUNNOW YET :C');
